# Custom Language File for Launcher Customizer

[ejs.app]
title = "Crafted Launcher Legacy"

[ejs.landing]
mediaGitHubURL = "https://github.com/Raft08/Crafted-Launcher-Legacy"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/HAJ2sza2AD"

[ejs.settings]
sourceGithubLink = "https://github.com/dscalZi/HeliosLauncher"
supportLink = "https://github.com/Raft08/Crafted-Launcher-Legacy/issues"

[ejs.welcome]
welcomeHeader = "WELCOME TO CRAFTED"
welcomeDescription = "Welcome to Belgian Nation"
welcomeDescCTA = "Continue"
